---
title: "Plotting Current Data"
author: "Helen Miller"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Plotting Current Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE,
  fig.width = 7,
  fig.height = 7
)
```

`AirMonitorPlots` provides functions to easily generate stylized plots of current data. 


```{r loadData}
library(AirMonitor)
library(AirMonitorPlots)
# Load current Data
mts_monitor <- monitor_loadLatest()
```

```{r}
# Set parameters
deviceDeploymentID <- "0b97822d89739950_060631010"
enddate <- lubridate::now()
startdate <- enddate - lubridate::ddays(7)
```

## Timeseries

```{r}
monitor_ggTimeseries(
  mts_monitor,
  startdate = startdate,
  enddate = enddate,
  deviceDeploymentIDs = deviceDeploymentID
)
```

## Daily Barplots

```{r}
monitor_ggDailyBarplot(
  mts_monitor,
  startdate = startdate,
  enddate = enddate,
  deviceDeploymentID = deviceDeploymentID
)
```

## Diurnal (dailyByHour)

```{r}
monitor_ggDailyByHour(
  mts_monitor,
  startdate = startdate,
  enddate = enddate,
  deviceDeploymentID = deviceDeploymentID
) 
```
